//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenBankingApiTester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QWACFile {
            get {
                return ((string)(this["QWACFile"]));
            }
            set {
                this["QWACFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QSEALFile {
            get {
                return ((string)(this["QSEALFile"]));
            }
            set {
                this["QSEALFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://somebank.com:444/psd2/v1/consents")]
        public string RequestUrl {
            get {
                return ((string)(this["RequestUrl"]));
            }
            set {
                this["RequestUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"access\": {\r\n    \"accounts\": []\r\n  },\r\n  \"recurringIndicator\": false,\r\n  \"va" +
            "lidUntil\": \"2021-01-01\",\r\n  \"frequencyPerDay\": 1,\r\n  \"combinedServiceIndicator\":" +
            " false\r\n}")]
        public string RequstBody {
            get {
                return ((string)(this["RequstBody"]));
            }
            set {
                this["RequstBody"] = value;
            }
        }
    }
}
